Responsiveness home fixed
Program-AR/pilas-bloques-react pull request #23
Opened 2023-04-25 18:02 UTC by danielferro69

Resolves https://github.com/Program-AR/pilas-bloques/issues/1315

https://user-images.githubusercontent.com/91342656/234363197-4cb70034-13f0-4da4-ab70-29c4fbb167a4.mp4

2023-04-26 14:12 UTC, asanzo reviewed
:clap: :clap: :clap: :clap: :clap: :clap: 
Laburazo, como siempre!! Fijate los comments que hice si tienen sentido o estoy medio fumado.

Hay una cosa que te debo si sucedía de antes pero noté ahora que es que en la consola hay un error:

![imagen](https://user-images.githubusercontent.com/5421992/234602431-892b06fc-8b1b-4e38-88a5-8306ede0c56a.png)

2023-04-26 14:12 UTC, asanzo commented on src/components/home/home.module.css
> +}
Y, para completar mi comment de arriba, me pregunto si estas cosas no se pueden en realidad resolver usando siempre los breakpoints de MUI.

2023-04-26 15:02 UTC, danielferro69 commented on src/components/footer/Footer.tsx
> +//spacing={12}
jajajaj ! de tantas pruebas, me quedó el // ahi ajjaja!

2023-04-26 15:15 UTC, danielferro69 commented on src/components/footer/footer.module.css
> +@media (max-width: 767px) {
Ahora entiendo por donde venian tus valores... en MUI los valores xs, sm etc son esos que estan definidos en [breakpoints](https://mui.com/material-ui/customization/breakpoints/#custom-breakpoints) como vos decis. El PROBLEMA mio es que yo tengo en la cabeza los valores de [bootstrap - w3schools](https://www.w3schools.com/bootstrap/bootstrap_grid_system.asp#:~:text=The%20Bootstrap%20grid%20system%20has,or%20greater%20than%20992px%20wide) / [bootstrap - getbootstrap.com](https://getbootstrap.com/docs/5.0/layout/breakpoints/)

y aunque parezca mentira, tienen valores diferentes....

llevemoslo a los de MUI y en tal caso, usaremos los breakpoints ya definidos. Le doy una iteracion para tratar de cerrarlo un poco mas... tambien habiamos hablado de llevar todo a un unico css que no se si sigue la idea de hacerlo asi para no tener css desparramados (home, header, footer) ... lo vemos.

2023-04-26 15:15 UTC, danielferro69 commented on src/components/home/home.module.css
> +}
si si, tengo que ver los nombres del theme y tratar, como decia mas arriba.

2023-04-26 15:31 UTC, danielferro69 commented
Respecto a los errores en consola, no los habia visto. El problema es que en MUI al usar `<Typography>` (en realidad es `<p>`)  con `<div>` adentro no le gusta...  que es lo que tuve que agregar con los links para darle estilo en el footer... tengo q cambiarlo a `<span>`

esto

`return <div className={styles['footer-links']}>
        <Link to="acercade" target="_blank">{t("aboutPilasBloques")}</Link> |
        <Link to="https://pilasbloques.program.ar/docentes" target="_blank"> {t("toTeachersSite")}</Link> |
        <Link to={termsAndConditionsLink} target="_blank"> {t("terms")}</Link>
    </div>`

por esto

`return <span className={styles['footer-links']}>
        <Link to="acercade" target="_blank">{t("aboutPilasBloques")}</Link> |
        <Link to="https://pilasbloques.program.ar/docentes" target="_blank"> {t("toTeachersSite")}</Link> |
        <Link to={termsAndConditionsLink} target="_blank"> {t("terms")}</Link>
    </span>`


[issue en stackoverflow.com](https://stackoverflow.com/questions/41928567/div-cannot-appear-as-a-descendant-of-p)

2023-04-27 04:54 UTC, asanzo commented on src/components/footer/footer.module.css
> +@media (max-width: 767px) {
Jajajajajaj excelente.

Repito: no me importa tanto cuáles son los valores (después vamos a jugar con ellos), lo importante es tocar en 1 sólo lugar para cambiarlos.

Sobre mi comentario de "unificar": La idea de que el css vaya asociado al componente sobre el cual trabaja no me molesta, de hecho es una buena práctica: si yo quiero cambiar el color de un botón es una paja tener que ir a un css general App.css a buscarlo en un quilombo perdido. Está bueno que button.css y Button.tsx estén cerquita, o bien si es poco css podemos tenerlo incluso todo dentro de Button.tsx si quieren simplificar.

Lo que yo decía es que por ejemplo _la posición_ del button en una pantalla más compleja, donde su ubicación tiene sentido en una pantalla enorme y en colaboración con otros botones y componentes, si yo pongo esa data de la posición en Button.css y la del componente superior en container.css y la del botón de al lado en otro archivo, luego termina pasando que esos están imposibles de encontrar. En un ideal podríamos tener:

```scss
// En ButtonOk.css cómo se ve el botón
#buttonOk {
    color: green,
    border-radius: 10px
}

// En ButtonCancel.css cómo se ve el botón
#buttonCancel {
   color: red
}

// En Dialog.css la estrategia para mostrarlo en el Dialog
#dialog {
     display: flex,
     flex-direction: row
},
#buttonCancel {
      order: 1
},
#buttonOk { 
      order: 2,  // este order tiene sentido en este contexto de Dialog, si yo lo pongo en button.css quien lea ese archivo no va a entender por qué tiene order 2.
      flex-grow: 2
}
```

Hay [bocha de formas](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Organizing) de organizar estilos. No hace falta que sigamos alguna en particular (ni la que propongo arriba), pero sí que al ir creciendo lo hagamos coherentemente, eso me preocupa más.

2023-04-28 13:47 UTC, asanzo approved these changes

2023-05-02 22:12 UTC, danielferro69 commented
@asanzo cuando puedas, podras pegarle una ultima revisada con lo que commitié?

2023-05-04 00:23 UTC, asanzo requested changes
EXCELENTE por lograr que todos los cortes sucedan a la vez sin repetir esa lógica.
Qué lástima que no existan en todos los componentes cosas tan bellas como en el grid que tenés el `{ sm: {color:red} }` y no tenés que poner toda la mediaquery verbosa.

Guarda a las cosas que marqué, puse un request changes porque me parece importante no mergear con eso así.

2023-05-04 00:23 UTC, asanzo commented on src/components/footer/Footer.tsx
> +                                                    }}}>Versión 1.2.3 - pepita</Typography>
![imagen](https://user-images.githubusercontent.com/5421992/236076434-e6c07500-4246-41b4-823f-11227bb22cd0.png)

Guarda que quedó un fontsize que sobreescribe el de footer.css (queda enorme), y con demasiado padding. Yo no tocaría demasiado esto, cargué un issue para verlo dsps:

https://github.com/Program-AR/pilas-bloques/issues/1321

2023-05-04 11:49 UTC, danielferro69 commented on src/components/footer/Footer.tsx
> +                                                    }}}>Versión 1.2.3 - pepita</Typography>
ok, no hay problema, lo revemos despues con los merge que estan pendientes mejor.

2023-05-04 11:52 UTC, danielferro69 commented on src/components/footer/Footer.tsx
> +    </Box>
Para que queden los links hay que darle un entorno diferente al footer. El tema es que en los Box no se puede hacer el cambio de row a column. Ya lo probé y no queda bien. Voy a ver si lo cambio por Stack y no pincha el resto. Los problemas en el cambio de resolucion generan que despues quede bien el celu y mal la web.
Respecto a display: block, si, se puede sacar y que asuma lo que venga heredado. Lo mismo que en otros que dejé inherit porque no sabia si despues volvia a los valores correctos, nada mas que por eso, pero si, podemos achicar el codigo y hacerlo en una linea.

2023-05-04 11:52 UTC, danielferro69 commented on src/components/footer/Footer.tsx
> +    <Stack direction={'row'} spacing={12} justifyContent={"center"} sx={{ padding: '10px'}}>
lo probamos y vemos como queda

2023-05-04 11:54 UTC, danielferro69 commented on src/components/header/Header.tsx
> +                      }}}>
uh... cierto.... El tema es que queda horrible y no hay manera de menterlo en un stack para que cambie de row a column. No logré que quedara lindo.
Quiza aca haya que iterar un poner un menu hamburguesa en lugar de todo eso cuando esta reducido por el celu.

2023-05-04 11:55 UTC, danielferro69 commented on src/components/home/Home.tsx
> +                            display: 'none' } }}>{t('tool')}</Typography>
lo forzamos. Son ajustes que hace el "acomodador" de codigo de vs. Pero no es un problema. Ademas quitando el default, podemos hacer q quede en una linea.

2023-05-04 13:16 UTC, asanzo commented on src/components/home/Home.tsx
> +                            display: 'none' } }}>{t('tool')}</Typography>
Sí, estaba pensando en el acomodador. Mepa que tenemos que hacer parte de lo que dice Tom y compartir las configuraciones para que arme esto mejor. Igual quiero que se entienda, no quiero un oneliner siempre o enters siempre, estaba pensando que no entendía bien la forma de separar el código y claro, lo hizo el acomodador.

2023-05-04 13:37 UTC, asanzo commented on src/components/footer/Footer.tsx
> +    </Box>
Genial!!
Perdón que rompa los huevos, un poco quiero aprovechar estos lugares pavos para de a poquito ir teniendo las discusiones que después en otro lugar más grande serían difíciles de tener. O sea, vale discutirme, sólo aprovecho para contarte las justificaciones que solemos usar para programar de tal o cual forma.

- Sobre el display:block, sí, está bueno no poner cosas que no se necesitan. Tiene 2 problemas: 1) hace que sea más difícil entender la lógica (más  y 2) la persona que viene atrás lo deja por miedo a romper, confía en que si lo pusiste es porque es necesario. Al sacar lo redundante, se evitan estos dos problemas mentales.
- Sobre los links, hay que mostrarlos siempre. Si en principio se cortan o quedan feúchos molesta menos que que desaparezcan, a eso me refería. O se puede pensar en un stack o un grid, como digas :+1:

2023-05-04 13:41 UTC, danielferro69 commented on src/components/footer/Footer.tsx
> +    </Box>
ta perfecto !!! olvidate !!! lo arreglamos. La idea es que quede bien !! y por ahora, `lo mejor posible` es `approved`

2023-05-04 14:18 UTC, danielferro69 commented on src/components/footer/Footer.tsx
> +                                                    }}}>Versión 1.2.3 - pepita</Typography>
Hecho

2023-05-04 14:19 UTC, danielferro69 commented on src/components/footer/Footer.tsx
> +    </Box>
hecho

2023-05-04 20:06 UTC, asanzo approved these changes
Bueno, me lo pude bajar y probar. Me gusta muchísimo cómo quedó :rocket: tanto la app como el código. Gracias :heart:

2023-05-04 20:07 UTC, merged